# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\os-hw1\view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
'''莫得灵魂的GUI'''

from PyQt5 import QtCore, QtGui, QtWidgets

class EView(object):
    def setupUi(self, Elevator):
        Elevator.setObjectName("电梯模拟器")
        # Elevator.resize(940, 784)
        self.ElevatorLayout = QtWidgets.QGridLayout(Elevator)
        self.ElevatorLayout.setObjectName("ElevatorLayout")
        self.inView = QtWidgets.QGroupBox(Elevator)
        self.inView.setObjectName("inView")
        self.inViewLayout = QtWidgets.QGridLayout(self.inView)
        self.inViewLayout.setObjectName("inViewLayout")
        self.tab = QtWidgets.QTabWidget(self.inView)
        self.tab.setObjectName("tab")
        self.elev0 = QtWidgets.QWidget()
        self.elev0.setObjectName("elev0")
        self.elev0Layout = QtWidgets.QGridLayout(self.elev0)
        self.elev0Layout.setObjectName("elev0Layout")
        self.elev_0_7 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_7.setCheckable(True)
        self.elev_0_7.setObjectName("elev_0_7")
        self.elev0Layout.addWidget(self.elev_0_7, 4, 4, 1, 1)
        self.elev_0_repair = QtWidgets.QPushButton(self.elev0)
        self.elev_0_repair.setCheckable(True)
        self.elev_0_repair.setObjectName("elev_0_repair")
        self.elev0Layout.addWidget(self.elev_0_repair, 0, 4, 1, 1)
        self.elev_0_15 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_15.setCheckable(True)
        self.elev_0_15.setObjectName("elev_0_15")
        self.elev0Layout.addWidget(self.elev_0_15, 2, 4, 1, 1)
        self.elev_0_4 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_4.setCheckable(True)
        self.elev_0_4.setObjectName("elev_0_4")
        self.elev0Layout.addWidget(self.elev_0_4, 4, 0, 1, 1)
        self.elev_0_1 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_1.setCheckable(True)
        self.elev_0_1.setObjectName("elev_0_1")
        self.elev0Layout.addWidget(self.elev_0_1, 5, 1, 1, 1)
        self.elev_0_10 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_10.setCheckable(True)
        self.elev_0_10.setObjectName("elev_0_10")
        self.elev0Layout.addWidget(self.elev_0_10, 3, 3, 1, 1)
        self.elev_0_8 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_8.setCheckable(True)
        self.elev_0_8.setObjectName("elev_0_8")
        self.elev0Layout.addWidget(self.elev_0_8, 3, 0, 1, 1)
        self.elev_0_lcd = QtWidgets.QLCDNumber(self.elev0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.elev_0_lcd.sizePolicy().hasHeightForWidth())
        self.elev_0_lcd.setSizePolicy(sizePolicy)
        self.elev_0_lcd.setStyleSheet("color: rgb(255, 0, 0);")
        self.elev_0_lcd.setDigitCount(2)
        self.elev_0_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elev_0_lcd.setProperty("intValue", 1)
        self.elev_0_lcd.setObjectName("elev_0_lcd")
        self.elev0Layout.addWidget(self.elev_0_lcd, 0, 0, 1, 1)
        self.elev_0_2 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_2.setCheckable(True)
        self.elev_0_2.setObjectName("elev_0_2")
        self.elev0Layout.addWidget(self.elev_0_2, 5, 3, 1, 1)
        self.elev_0_6 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_6.setCheckable(True)
        self.elev_0_6.setObjectName("elev_0_6")
        self.elev0Layout.addWidget(self.elev_0_6, 4, 3, 1, 1)
        self.elev_0_17 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_17.setCheckable(True)
        self.elev_0_17.setObjectName("elev_0_17")
        self.elev0Layout.addWidget(self.elev_0_17, 1, 1, 1, 1)
        self.elev_0_11 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_11.setCheckable(True)
        self.elev_0_11.setObjectName("elev_0_11")
        self.elev0Layout.addWidget(self.elev_0_11, 3, 4, 1, 1)
        self.elev_0_12 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_12.setCheckable(True)
        self.elev_0_12.setObjectName("elev_0_12")
        self.elev0Layout.addWidget(self.elev_0_12, 2, 0, 1, 1)
        self.elev_0_close = QtWidgets.QPushButton(self.elev0)
        self.elev_0_close.setCheckable(True)
        self.elev_0_close.setObjectName("elev_0_close")
        self.elev0Layout.addWidget(self.elev_0_close, 0, 3, 1, 1)
        self.elev_0_19 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_19.setCheckable(True)
        self.elev_0_19.setObjectName("elev_0_19")
        self.elev0Layout.addWidget(self.elev_0_19, 1, 4, 1, 1)
        self.elev_0_open = QtWidgets.QPushButton(self.elev0)
        self.elev_0_open.setCheckable(True)
        self.elev_0_open.setObjectName("elev_0_open")
        self.elev0Layout.addWidget(self.elev_0_open, 0, 1, 1, 1)
        self.elev_0_5 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_5.setCheckable(True)
        self.elev_0_5.setObjectName("elev_0_5")
        self.elev0Layout.addWidget(self.elev_0_5, 4, 1, 1, 1)
        self.elev_0_0 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_0.setCheckable(True)
        self.elev_0_0.setObjectName("elev_0_0")
        self.elev0Layout.addWidget(self.elev_0_0, 5, 0, 1, 1)
        self.elev_0_3 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_3.setCheckable(True)
        self.elev_0_3.setObjectName("elev_0_3")
        self.elev0Layout.addWidget(self.elev_0_3, 5, 4, 1, 1)
        self.elev_0_9 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_9.setCheckable(True)
        self.elev_0_9.setObjectName("elev_0_9")
        self.elev0Layout.addWidget(self.elev_0_9, 3, 1, 1, 1)
        self.elev_0_13 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_13.setCheckable(True)
        self.elev_0_13.setObjectName("elev_0_13")
        self.elev0Layout.addWidget(self.elev_0_13, 2, 1, 1, 1)
        self.elev_0_14 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_14.setCheckable(True)
        self.elev_0_14.setObjectName("elev_0_14")
        self.elev0Layout.addWidget(self.elev_0_14, 2, 3, 1, 1)
        self.elev_0_18 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_18.setCheckable(True)
        self.elev_0_18.setObjectName("elev_0_18")
        self.elev0Layout.addWidget(self.elev_0_18, 1, 3, 1, 1)
        self.elev_0_16 = QtWidgets.QPushButton(self.elev0)
        self.elev_0_16.setCheckable(True)
        self.elev_0_16.setObjectName("elev_0_16")
        self.elev0Layout.addWidget(self.elev_0_16, 1, 0, 1, 1)
        self.tab.addTab(self.elev0, "")
        self.elev1 = QtWidgets.QWidget()
        self.elev1.setObjectName("elev1")
        self.elev1Layout = QtWidgets.QGridLayout(self.elev1)
        self.elev1Layout.setObjectName("elev1Layout")
        self.elev_1_lcd = QtWidgets.QLCDNumber(self.elev1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.elev_1_lcd.sizePolicy().hasHeightForWidth())
        self.elev_1_lcd.setSizePolicy(sizePolicy)
        self.elev_1_lcd.setStyleSheet("color: rgb(255, 0, 0);")
        self.elev_1_lcd.setDigitCount(2)
        self.elev_1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elev_1_lcd.setProperty("intValue", 1)
        self.elev_1_lcd.setObjectName("elev_1_lcd")
        self.elev1Layout.addWidget(self.elev_1_lcd, 0, 0, 1, 1)
        self.elev_1_open = QtWidgets.QPushButton(self.elev1)
        self.elev_1_open.setCheckable(True)
        self.elev_1_open.setObjectName("elev_1_open")
        self.elev1Layout.addWidget(self.elev_1_open, 0, 1, 1, 1)
        self.elev_1_close = QtWidgets.QPushButton(self.elev1)
        self.elev_1_close.setCheckable(True)
        self.elev_1_close.setObjectName("elev_1_close")
        self.elev1Layout.addWidget(self.elev_1_close, 0, 2, 1, 1)
        self.elev_1_repair = QtWidgets.QPushButton(self.elev1)
        self.elev_1_repair.setCheckable(True)
        self.elev_1_repair.setObjectName("elev_1_repair")
        self.elev1Layout.addWidget(self.elev_1_repair, 0, 3, 1, 1)
        self.elev_1_16 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_16.setCheckable(True)
        self.elev_1_16.setObjectName("elev_1_16")
        self.elev1Layout.addWidget(self.elev_1_16, 1, 0, 1, 1)
        self.elev_1_17 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_17.setCheckable(True)
        self.elev_1_17.setObjectName("elev_1_17")
        self.elev1Layout.addWidget(self.elev_1_17, 1, 1, 1, 1)
        self.elev_1_18 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_18.setCheckable(True)
        self.elev_1_18.setObjectName("elev_1_18")
        self.elev1Layout.addWidget(self.elev_1_18, 1, 2, 1, 1)
        self.elev_1_19 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_19.setCheckable(True)
        self.elev_1_19.setObjectName("elev_1_19")
        self.elev1Layout.addWidget(self.elev_1_19, 1, 3, 1, 1)
        self.elev_1_12 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_12.setCheckable(True)
        self.elev_1_12.setObjectName("elev_1_12")
        self.elev1Layout.addWidget(self.elev_1_12, 2, 0, 1, 1)
        self.elev_1_13 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_13.setCheckable(True)
        self.elev_1_13.setObjectName("elev_1_13")
        self.elev1Layout.addWidget(self.elev_1_13, 2, 1, 1, 1)
        self.elev_1_14 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_14.setCheckable(True)
        self.elev_1_14.setObjectName("elev_1_14")
        self.elev1Layout.addWidget(self.elev_1_14, 2, 2, 1, 1)
        self.elev_1_15 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_15.setCheckable(True)
        self.elev_1_15.setObjectName("elev_1_15")
        self.elev1Layout.addWidget(self.elev_1_15, 2, 3, 1, 1)
        self.elev_1_8 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_8.setCheckable(True)
        self.elev_1_8.setObjectName("elev_1_8")
        self.elev1Layout.addWidget(self.elev_1_8, 3, 0, 1, 1)
        self.elev_1_9 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_9.setCheckable(True)
        self.elev_1_9.setObjectName("elev_1_9")
        self.elev1Layout.addWidget(self.elev_1_9, 3, 1, 1, 1)
        self.elev_1_10 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_10.setCheckable(True)
        self.elev_1_10.setObjectName("elev_1_10")
        self.elev1Layout.addWidget(self.elev_1_10, 3, 2, 1, 1)
        self.elev_1_11 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_11.setCheckable(True)
        self.elev_1_11.setObjectName("elev_1_11")
        self.elev1Layout.addWidget(self.elev_1_11, 3, 3, 1, 1)
        self.elev_1_4 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_4.setCheckable(True)
        self.elev_1_4.setObjectName("elev_1_4")
        self.elev1Layout.addWidget(self.elev_1_4, 4, 0, 1, 1)
        self.elev_1_5 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_5.setCheckable(True)
        self.elev_1_5.setObjectName("elev_1_5")
        self.elev1Layout.addWidget(self.elev_1_5, 4, 1, 1, 1)
        self.elev_1_6 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_6.setCheckable(True)
        self.elev_1_6.setObjectName("elev_1_6")
        self.elev1Layout.addWidget(self.elev_1_6, 4, 2, 1, 1)
        self.elev_1_7 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_7.setCheckable(True)
        self.elev_1_7.setObjectName("elev_1_7")
        self.elev1Layout.addWidget(self.elev_1_7, 4, 3, 1, 1)
        self.elev_1_0 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_0.setCheckable(True)
        self.elev_1_0.setObjectName("elev_1_0")
        self.elev1Layout.addWidget(self.elev_1_0, 5, 0, 1, 1)
        self.elev_1_1 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_1.setCheckable(True)
        self.elev_1_1.setObjectName("elev_1_1")
        self.elev1Layout.addWidget(self.elev_1_1, 5, 1, 1, 1)
        self.elev_1_2 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_2.setCheckable(True)
        self.elev_1_2.setObjectName("elev_1_2")
        self.elev1Layout.addWidget(self.elev_1_2, 5, 2, 1, 1)
        self.elev_1_3 = QtWidgets.QPushButton(self.elev1)
        self.elev_1_3.setCheckable(True)
        self.elev_1_3.setObjectName("elev_1_3")
        self.elev1Layout.addWidget(self.elev_1_3, 5, 3, 1, 1)
        self.tab.addTab(self.elev1, "")
        self.elev2 = QtWidgets.QWidget()
        self.elev2.setObjectName("elev2")
        self.elev2Layout = QtWidgets.QGridLayout(self.elev2)
        self.elev2Layout.setObjectName("elev2Layout")
        self.elev_2_lcd = QtWidgets.QLCDNumber(self.elev2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.elev_2_lcd.sizePolicy().hasHeightForWidth())
        self.elev_2_lcd.setSizePolicy(sizePolicy)
        self.elev_2_lcd.setStyleSheet("color: rgb(255, 0, 0);")
        self.elev_2_lcd.setDigitCount(2)
        self.elev_2_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elev_2_lcd.setProperty("intValue", 1)
        self.elev_2_lcd.setObjectName("elev_2_lcd")
        self.elev2Layout.addWidget(self.elev_2_lcd, 0, 0, 1, 1)
        self.elev_2_open = QtWidgets.QPushButton(self.elev2)
        self.elev_2_open.setCheckable(True)
        self.elev_2_open.setObjectName("elev_2_open")
        self.elev2Layout.addWidget(self.elev_2_open, 0, 1, 1, 1)
        self.elev_2_close = QtWidgets.QPushButton(self.elev2)
        self.elev_2_close.setCheckable(True)
        self.elev_2_close.setObjectName("elev_2_close")
        self.elev2Layout.addWidget(self.elev_2_close, 0, 2, 1, 1)
        self.elev_2_repair = QtWidgets.QPushButton(self.elev2)
        self.elev_2_repair.setCheckable(True)
        self.elev_2_repair.setObjectName("elev_2_repair")
        self.elev2Layout.addWidget(self.elev_2_repair, 0, 3, 1, 1)
        self.elev_2_16 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_16.setCheckable(True)
        self.elev_2_16.setObjectName("elev_2_16")
        self.elev2Layout.addWidget(self.elev_2_16, 1, 0, 1, 1)
        self.elev_2_17 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_17.setCheckable(True)
        self.elev_2_17.setObjectName("elev_2_17")
        self.elev2Layout.addWidget(self.elev_2_17, 1, 1, 1, 1)
        self.elev_2_18 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_18.setCheckable(True)
        self.elev_2_18.setObjectName("elev_2_18")
        self.elev2Layout.addWidget(self.elev_2_18, 1, 2, 1, 1)
        self.elev_2_19 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_19.setCheckable(True)
        self.elev_2_19.setObjectName("elev_2_19")
        self.elev2Layout.addWidget(self.elev_2_19, 1, 3, 1, 1)
        self.elev_2_12 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_12.setCheckable(True)
        self.elev_2_12.setObjectName("elev_2_12")
        self.elev2Layout.addWidget(self.elev_2_12, 2, 0, 1, 1)
        self.elev_2_13 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_13.setCheckable(True)
        self.elev_2_13.setObjectName("elev_2_13")
        self.elev2Layout.addWidget(self.elev_2_13, 2, 1, 1, 1)
        self.elev_2_14 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_14.setCheckable(True)
        self.elev_2_14.setObjectName("elev_2_14")
        self.elev2Layout.addWidget(self.elev_2_14, 2, 2, 1, 1)
        self.elev_2_15 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_15.setCheckable(True)
        self.elev_2_15.setObjectName("elev_2_15")
        self.elev2Layout.addWidget(self.elev_2_15, 2, 3, 1, 1)
        self.elev_2_8 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_8.setCheckable(True)
        self.elev_2_8.setObjectName("elev_2_8")
        self.elev2Layout.addWidget(self.elev_2_8, 3, 0, 1, 1)
        self.elev_2_9 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_9.setCheckable(True)
        self.elev_2_9.setObjectName("elev_2_9")
        self.elev2Layout.addWidget(self.elev_2_9, 3, 1, 1, 1)
        self.elev_2_10 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_10.setCheckable(True)
        self.elev_2_10.setObjectName("elev_2_10")
        self.elev2Layout.addWidget(self.elev_2_10, 3, 2, 1, 1)
        self.elev_2_11 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_11.setCheckable(True)
        self.elev_2_11.setObjectName("elev_2_11")
        self.elev2Layout.addWidget(self.elev_2_11, 3, 3, 1, 1)
        self.elev_2_4 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_4.setCheckable(True)
        self.elev_2_4.setObjectName("elev_2_4")
        self.elev2Layout.addWidget(self.elev_2_4, 4, 0, 1, 1)
        self.elev_2_5 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_5.setCheckable(True)
        self.elev_2_5.setObjectName("elev_2_5")
        self.elev2Layout.addWidget(self.elev_2_5, 4, 1, 1, 1)
        self.elev_2_6 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_6.setCheckable(True)
        self.elev_2_6.setObjectName("elev_2_6")
        self.elev2Layout.addWidget(self.elev_2_6, 4, 2, 1, 1)
        self.elev_2_7 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_7.setCheckable(True)
        self.elev_2_7.setObjectName("elev_2_7")
        self.elev2Layout.addWidget(self.elev_2_7, 4, 3, 1, 1)
        self.elev_2_0 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_0.setCheckable(True)
        self.elev_2_0.setObjectName("elev_2_0")
        self.elev2Layout.addWidget(self.elev_2_0, 5, 0, 1, 1)
        self.elev_2_1 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_1.setCheckable(True)
        self.elev_2_1.setObjectName("elev_2_1")
        self.elev2Layout.addWidget(self.elev_2_1, 5, 1, 1, 1)
        self.elev_2_2 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_2.setCheckable(True)
        self.elev_2_2.setObjectName("elev_2_2")
        self.elev2Layout.addWidget(self.elev_2_2, 5, 2, 1, 1)
        self.elev_2_3 = QtWidgets.QPushButton(self.elev2)
        self.elev_2_3.setCheckable(True)
        self.elev_2_3.setObjectName("elev_2_3")
        self.elev2Layout.addWidget(self.elev_2_3, 5, 3, 1, 1)
        self.tab.addTab(self.elev2, "")
        self.elev3 = QtWidgets.QWidget()
        self.elev3.setObjectName("elev3")
        self.elev3Layout = QtWidgets.QGridLayout(self.elev3)
        self.elev3Layout.setObjectName("elev3Layout")
        self.elev_3_lcd = QtWidgets.QLCDNumber(self.elev3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.elev_3_lcd.sizePolicy().hasHeightForWidth())
        self.elev_3_lcd.setSizePolicy(sizePolicy)
        self.elev_3_lcd.setStyleSheet("color: rgb(255, 0, 0);")
        self.elev_3_lcd.setDigitCount(2)
        self.elev_3_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elev_3_lcd.setProperty("intValue", 1)
        self.elev_3_lcd.setObjectName("elev_3_lcd")
        self.elev3Layout.addWidget(self.elev_3_lcd, 0, 0, 1, 1)
        self.elev_3_open = QtWidgets.QPushButton(self.elev3)
        self.elev_3_open.setCheckable(True)
        self.elev_3_open.setObjectName("elev_3_open")
        self.elev3Layout.addWidget(self.elev_3_open, 0, 1, 1, 1)
        self.elev_3_close = QtWidgets.QPushButton(self.elev3)
        self.elev_3_close.setCheckable(True)
        self.elev_3_close.setObjectName("elev_3_close")
        self.elev3Layout.addWidget(self.elev_3_close, 0, 2, 1, 1)
        self.elev_3_repair = QtWidgets.QPushButton(self.elev3)
        self.elev_3_repair.setCheckable(True)
        self.elev_3_repair.setObjectName("elev_3_repair")
        self.elev3Layout.addWidget(self.elev_3_repair, 0, 3, 1, 1)
        self.elev_3_16 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_16.setCheckable(True)
        self.elev_3_16.setObjectName("elev_3_16")
        self.elev3Layout.addWidget(self.elev_3_16, 1, 0, 1, 1)
        self.elev_3_17 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_17.setCheckable(True)
        self.elev_3_17.setObjectName("elev_3_17")
        self.elev3Layout.addWidget(self.elev_3_17, 1, 1, 1, 1)
        self.elev_3_18 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_18.setCheckable(True)
        self.elev_3_18.setObjectName("elev_3_18")
        self.elev3Layout.addWidget(self.elev_3_18, 1, 2, 1, 1)
        self.elev_3_19 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_19.setCheckable(True)
        self.elev_3_19.setObjectName("elev_3_19")
        self.elev3Layout.addWidget(self.elev_3_19, 1, 3, 1, 1)
        self.elev_3_12 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_12.setCheckable(True)
        self.elev_3_12.setObjectName("elev_3_12")
        self.elev3Layout.addWidget(self.elev_3_12, 2, 0, 1, 1)
        self.elev_3_13 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_13.setCheckable(True)
        self.elev_3_13.setObjectName("elev_3_13")
        self.elev3Layout.addWidget(self.elev_3_13, 2, 1, 1, 1)
        self.elev_3_14 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_14.setCheckable(True)
        self.elev_3_14.setObjectName("elev_3_14")
        self.elev3Layout.addWidget(self.elev_3_14, 2, 2, 1, 1)
        self.elev_3_15 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_15.setCheckable(True)
        self.elev_3_15.setObjectName("elev_3_15")
        self.elev3Layout.addWidget(self.elev_3_15, 2, 3, 1, 1)
        self.elev_3_8 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_8.setCheckable(True)
        self.elev_3_8.setObjectName("elev_3_8")
        self.elev3Layout.addWidget(self.elev_3_8, 3, 0, 1, 1)
        self.elev_3_9 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_9.setCheckable(True)
        self.elev_3_9.setObjectName("elev_3_9")
        self.elev3Layout.addWidget(self.elev_3_9, 3, 1, 1, 1)
        self.elev_3_10 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_10.setCheckable(True)
        self.elev_3_10.setObjectName("elev_3_10")
        self.elev3Layout.addWidget(self.elev_3_10, 3, 2, 1, 1)
        self.elev_3_11 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_11.setCheckable(True)
        self.elev_3_11.setObjectName("elev_3_11")
        self.elev3Layout.addWidget(self.elev_3_11, 3, 3, 1, 1)
        self.elev_3_4 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_4.setCheckable(True)
        self.elev_3_4.setObjectName("elev_3_4")
        self.elev3Layout.addWidget(self.elev_3_4, 4, 0, 1, 1)
        self.elev_3_5 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_5.setCheckable(True)
        self.elev_3_5.setObjectName("elev_3_5")
        self.elev3Layout.addWidget(self.elev_3_5, 4, 1, 1, 1)
        self.elev_3_6 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_6.setCheckable(True)
        self.elev_3_6.setObjectName("elev_3_6")
        self.elev3Layout.addWidget(self.elev_3_6, 4, 2, 1, 1)
        self.elev_3_7 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_7.setCheckable(True)
        self.elev_3_7.setObjectName("elev_3_7")
        self.elev3Layout.addWidget(self.elev_3_7, 4, 3, 1, 1)
        self.elev_3_0 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_0.setCheckable(True)
        self.elev_3_0.setObjectName("elev_3_0")
        self.elev3Layout.addWidget(self.elev_3_0, 5, 0, 1, 1)
        self.elev_3_1 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_1.setCheckable(True)
        self.elev_3_1.setObjectName("elev_3_1")
        self.elev3Layout.addWidget(self.elev_3_1, 5, 1, 1, 1)
        self.elev_3_2 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_2.setCheckable(True)
        self.elev_3_2.setObjectName("elev_3_2")
        self.elev3Layout.addWidget(self.elev_3_2, 5, 2, 1, 1)
        self.elev_3_3 = QtWidgets.QPushButton(self.elev3)
        self.elev_3_3.setCheckable(True)
        self.elev_3_3.setObjectName("elev_3_3")
        self.elev3Layout.addWidget(self.elev_3_3, 5, 3, 1, 1)
        self.tab.addTab(self.elev3, "")
        self.elev4 = QtWidgets.QWidget()
        self.elev4.setObjectName("elev4")
        self.elev4Layout = QtWidgets.QGridLayout(self.elev4)
        self.elev4Layout.setObjectName("elev4Layout")
        self.elev_4_lcd = QtWidgets.QLCDNumber(self.elev4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.elev_4_lcd.sizePolicy().hasHeightForWidth())
        self.elev_4_lcd.setSizePolicy(sizePolicy)
        self.elev_4_lcd.setStyleSheet("color: rgb(255, 0, 0);")
        self.elev_4_lcd.setDigitCount(2)
        self.elev_4_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elev_4_lcd.setProperty("intValue", 1)
        self.elev_4_lcd.setObjectName("elev_4_lcd")
        self.elev4Layout.addWidget(self.elev_4_lcd, 0, 0, 1, 1)
        self.elev_4_open = QtWidgets.QPushButton(self.elev4)
        self.elev_4_open.setCheckable(True)
        self.elev_4_open.setObjectName("elev_4_open")
        self.elev4Layout.addWidget(self.elev_4_open, 0, 1, 1, 1)
        self.elev_4_close = QtWidgets.QPushButton(self.elev4)
        self.elev_4_close.setCheckable(True)
        self.elev_4_close.setObjectName("elev_4_close")
        self.elev4Layout.addWidget(self.elev_4_close, 0, 2, 1, 1)
        self.elev_4_repair = QtWidgets.QPushButton(self.elev4)
        self.elev_4_repair.setCheckable(True)
        self.elev_4_repair.setObjectName("elev_4_repair")
        self.elev4Layout.addWidget(self.elev_4_repair, 0, 3, 1, 1)
        self.elev_4_16 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_16.setCheckable(True)
        self.elev_4_16.setObjectName("elev_4_16")
        self.elev4Layout.addWidget(self.elev_4_16, 1, 0, 1, 1)
        self.elev_4_17 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_17.setCheckable(True)
        self.elev_4_17.setObjectName("elev_4_17")
        self.elev4Layout.addWidget(self.elev_4_17, 1, 1, 1, 1)
        self.elev_4_18 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_18.setCheckable(True)
        self.elev_4_18.setObjectName("elev_4_18")
        self.elev4Layout.addWidget(self.elev_4_18, 1, 2, 1, 1)
        self.elev_4_19 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_19.setCheckable(True)
        self.elev_4_19.setObjectName("elev_4_19")
        self.elev4Layout.addWidget(self.elev_4_19, 1, 3, 1, 1)
        self.elev_4_12 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_12.setCheckable(True)
        self.elev_4_12.setObjectName("elev_4_12")
        self.elev4Layout.addWidget(self.elev_4_12, 2, 0, 1, 1)
        self.elev_4_13 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_13.setCheckable(True)
        self.elev_4_13.setObjectName("elev_4_13")
        self.elev4Layout.addWidget(self.elev_4_13, 2, 1, 1, 1)
        self.elev_4_14 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_14.setCheckable(True)
        self.elev_4_14.setObjectName("elev_4_14")
        self.elev4Layout.addWidget(self.elev_4_14, 2, 2, 1, 1)
        self.elev_4_15 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_15.setCheckable(True)
        self.elev_4_15.setObjectName("elev_4_15")
        self.elev4Layout.addWidget(self.elev_4_15, 2, 3, 1, 1)
        self.elev_4_8 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_8.setCheckable(True)
        self.elev_4_8.setObjectName("elev_4_8")
        self.elev4Layout.addWidget(self.elev_4_8, 3, 0, 1, 1)
        self.elev_4_9 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_9.setCheckable(True)
        self.elev_4_9.setObjectName("elev_4_9")
        self.elev4Layout.addWidget(self.elev_4_9, 3, 1, 1, 1)
        self.elev_4_10 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_10.setCheckable(True)
        self.elev_4_10.setObjectName("elev_4_10")
        self.elev4Layout.addWidget(self.elev_4_10, 3, 2, 1, 1)
        self.elev_4_11 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_11.setCheckable(True)
        self.elev_4_11.setObjectName("elev_4_11")
        self.elev4Layout.addWidget(self.elev_4_11, 3, 3, 1, 1)
        self.elev_4_4 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_4.setCheckable(True)
        self.elev_4_4.setObjectName("elev_4_4")
        self.elev4Layout.addWidget(self.elev_4_4, 4, 0, 1, 1)
        self.elev_4_5 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_5.setCheckable(True)
        self.elev_4_5.setObjectName("elev_4_5")
        self.elev4Layout.addWidget(self.elev_4_5, 4, 1, 1, 1)
        self.elev_4_6 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_6.setCheckable(True)
        self.elev_4_6.setObjectName("elev_4_6")
        self.elev4Layout.addWidget(self.elev_4_6, 4, 2, 1, 1)
        self.elev_4_7 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_7.setCheckable(True)
        self.elev_4_7.setObjectName("elev_4_7")
        self.elev4Layout.addWidget(self.elev_4_7, 4, 3, 1, 1)
        self.elev_4_0 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_0.setCheckable(True)
        self.elev_4_0.setObjectName("elev_4_0")
        self.elev4Layout.addWidget(self.elev_4_0, 5, 0, 1, 1)
        self.elev_4_1 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_1.setCheckable(True)
        self.elev_4_1.setObjectName("elev_4_1")
        self.elev4Layout.addWidget(self.elev_4_1, 5, 1, 1, 1)
        self.elev_4_2 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_2.setCheckable(True)
        self.elev_4_2.setObjectName("elev_4_2")
        self.elev4Layout.addWidget(self.elev_4_2, 5, 2, 1, 1)
        self.elev_4_3 = QtWidgets.QPushButton(self.elev4)
        self.elev_4_3.setCheckable(True)
        self.elev_4_3.setObjectName("elev_4_3")
        self.elev4Layout.addWidget(self.elev_4_3, 5, 3, 1, 1)
        self.tab.addTab(self.elev4, "")
        self.inViewLayout.addWidget(self.tab, 2, 0, 1, 1)
        self.ElevatorLayout.addWidget(self.inView, 1, 1, 1, 1)
        self.msgBox = QtWidgets.QGroupBox(Elevator)
        self.msgBox.setObjectName("msgBox")
        self.msgBoxLayout = QtWidgets.QVBoxLayout(self.msgBox)
        self.msgBoxLayout.setObjectName("msgBoxLayout")
        self.logger = QtWidgets.QTextBrowser(self.msgBox)
        self.logger.setObjectName("logger")
        self.msgBoxLayout.addWidget(self.logger)
        self.ElevatorLayout.addWidget(self.msgBox, 2, 1, 1, 1)
        self.outView = QtWidgets.QGroupBox(Elevator)
        self.outView.setStyleSheet("QSlider::groove {\n"
"border: 1px solid #999999;\n"
"width: 5px;\n"
"}\n"
"QSlider::handle {\n"
"background: green;\n"
"height: 30px;\n"
"margin: 0 -15px;\n"
"border: 1px solid grey;\n"
"}")
        self.outView.setObjectName("outView")
        self.gridLayout = QtWidgets.QGridLayout(self.outView)
        self.gridLayout.setObjectName("gridLayout")
        self.down_3 = QtWidgets.QPushButton(self.outView)
        self.down_3.setCheckable(True)
        self.down_3.setObjectName("down_3")
        self.gridLayout.addWidget(self.down_3, 17, 7, 1, 1)
        self.down_6 = QtWidgets.QPushButton(self.outView)
        self.down_6.setCheckable(True)
        self.down_6.setObjectName("down_6")
        self.gridLayout.addWidget(self.down_6, 14, 7, 1, 1)
        self.lcd_0 = QtWidgets.QLCDNumber(self.outView)
        self.lcd_0.setStyleSheet("color: rgb(255, 0, 0);")
        self.lcd_0.setDigitCount(2)
        self.lcd_0.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_0.setProperty("intValue", 1)
        self.lcd_0.setObjectName("lcd_0")
        self.gridLayout.addWidget(self.lcd_0, 0, 1, 1, 1)
        self.up_13 = QtWidgets.QPushButton(self.outView)
        self.up_13.setCheckable(True)
        self.up_13.setObjectName("up_13")
        self.gridLayout.addWidget(self.up_13, 7, 6, 1, 1)
        self.down_11 = QtWidgets.QPushButton(self.outView)
        self.down_11.setCheckable(True)
        self.down_11.setObjectName("down_11")
        self.gridLayout.addWidget(self.down_11, 9, 7, 1, 1)
        self.down_12 = QtWidgets.QPushButton(self.outView)
        self.down_12.setCheckable(True)
        self.down_12.setObjectName("down_12")
        self.gridLayout.addWidget(self.down_12, 8, 7, 1, 1)
        self.up_2 = QtWidgets.QPushButton(self.outView)
        self.up_2.setCheckable(True)
        self.up_2.setObjectName("up_2")
        self.gridLayout.addWidget(self.up_2, 18, 6, 1, 1)
        self.up_17 = QtWidgets.QPushButton(self.outView)
        self.up_17.setCheckable(True)
        self.up_17.setObjectName("up_17")
        self.gridLayout.addWidget(self.up_17, 3, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.outView)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.outView)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.down_14 = QtWidgets.QPushButton(self.outView)
        self.down_14.setCheckable(True)
        self.down_14.setObjectName("down_14")
        self.gridLayout.addWidget(self.down_14, 6, 7, 1, 1)
        self.lcd_4 = QtWidgets.QLCDNumber(self.outView)
        self.lcd_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.lcd_4.setDigitCount(2)
        self.lcd_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_4.setProperty("intValue", 1)
        self.lcd_4.setObjectName("lcd_4")
        self.gridLayout.addWidget(self.lcd_4, 0, 5, 1, 1)
        self.up_4 = QtWidgets.QPushButton(self.outView)
        self.up_4.setCheckable(True)
        self.up_4.setObjectName("up_4")
        self.gridLayout.addWidget(self.up_4, 16, 6, 1, 1)
        self.slider_1 = QtWidgets.QSlider(self.outView)
        self.slider_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_1.sizePolicy().hasHeightForWidth())
        self.slider_1.setSizePolicy(sizePolicy)
        self.slider_1.setMaximum(19)
        self.slider_1.setObjectName("slider_1")
        self.gridLayout.addWidget(self.slider_1, 1, 2, 20, 1)
        self.up_6 = QtWidgets.QPushButton(self.outView)
        self.up_6.setCheckable(True)
        self.up_6.setObjectName("up_6")
        self.gridLayout.addWidget(self.up_6, 14, 6, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.outView)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.down_9 = QtWidgets.QPushButton(self.outView)
        self.down_9.setCheckable(True)
        self.down_9.setObjectName("down_9")
        self.gridLayout.addWidget(self.down_9, 11, 7, 1, 1)
        self.slider_4 = QtWidgets.QSlider(self.outView)
        self.slider_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_4.sizePolicy().hasHeightForWidth())
        self.slider_4.setSizePolicy(sizePolicy)
        self.slider_4.setMaximum(19)
        self.slider_4.setObjectName("slider_4")
        self.gridLayout.addWidget(self.slider_4, 1, 5, 20, 1)
        self.up_18 = QtWidgets.QPushButton(self.outView)
        self.up_18.setCheckable(True)
        self.up_18.setObjectName("up_18")
        self.gridLayout.addWidget(self.up_18, 2, 6, 1, 1)
        self.down_16 = QtWidgets.QPushButton(self.outView)
        self.down_16.setCheckable(True)
        self.down_16.setObjectName("down_16")
        self.gridLayout.addWidget(self.down_16, 4, 7, 1, 1)
        self.slider_0 = QtWidgets.QSlider(self.outView)
        self.slider_0.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_0.sizePolicy().hasHeightForWidth())
        self.slider_0.setSizePolicy(sizePolicy)
        self.slider_0.setStyleSheet("")
        self.slider_0.setMaximum(19)
        self.slider_0.setObjectName("slider_0")
        self.gridLayout.addWidget(self.slider_0, 1, 1, 20, 1)
        self.down_0 = QtWidgets.QPushButton(self.outView)
        self.down_0.setEnabled(False)
        self.down_0.setCheckable(True)
        self.down_0.setObjectName("down_0")
        self.gridLayout.addWidget(self.down_0, 20, 7, 1, 1)
        self.down_7 = QtWidgets.QPushButton(self.outView)
        self.down_7.setCheckable(True)
        self.down_7.setObjectName("down_7")
        self.gridLayout.addWidget(self.down_7, 13, 7, 1, 1)
        self.down_8 = QtWidgets.QPushButton(self.outView)
        self.down_8.setCheckable(True)
        self.down_8.setObjectName("down_8")
        self.gridLayout.addWidget(self.down_8, 12, 7, 1, 1)
        self.up_7 = QtWidgets.QPushButton(self.outView)
        self.up_7.setCheckable(True)
        self.up_7.setObjectName("up_7")
        self.gridLayout.addWidget(self.up_7, 13, 6, 1, 1)
        self.down_19 = QtWidgets.QPushButton(self.outView)
        self.down_19.setCheckable(True)
        self.down_19.setObjectName("down_19")
        self.gridLayout.addWidget(self.down_19, 1, 7, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.outView)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 12, 0, 1, 1)
        self.up_5 = QtWidgets.QPushButton(self.outView)
        self.up_5.setCheckable(True)
        self.up_5.setObjectName("up_5")
        self.gridLayout.addWidget(self.up_5, 15, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.outView)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 7, 0, 1, 1)
        self.up_16 = QtWidgets.QPushButton(self.outView)
        self.up_16.setCheckable(True)
        self.up_16.setObjectName("up_16")
        self.gridLayout.addWidget(self.up_16, 4, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.outView)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 18, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.outView)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 17, 0, 1, 1)
        self.up_15 = QtWidgets.QPushButton(self.outView)
        self.up_15.setCheckable(True)
        self.up_15.setObjectName("up_15")
        self.gridLayout.addWidget(self.up_15, 5, 6, 1, 1)
        self.up_11 = QtWidgets.QPushButton(self.outView)
        self.up_11.setCheckable(True)
        self.up_11.setObjectName("up_11")
        self.gridLayout.addWidget(self.up_11, 9, 6, 1, 1)
        self.up_9 = QtWidgets.QPushButton(self.outView)
        self.up_9.setCheckable(True)
        self.up_9.setObjectName("up_9")
        self.gridLayout.addWidget(self.up_9, 11, 6, 1, 1)
        self.up_14 = QtWidgets.QPushButton(self.outView)
        self.up_14.setCheckable(True)
        self.up_14.setObjectName("up_14")
        self.gridLayout.addWidget(self.up_14, 6, 6, 1, 1)
        self.up_8 = QtWidgets.QPushButton(self.outView)
        self.up_8.setCheckable(True)
        self.up_8.setObjectName("up_8")
        self.gridLayout.addWidget(self.up_8, 12, 6, 1, 1)
        self.up_19 = QtWidgets.QPushButton(self.outView)
        self.up_19.setEnabled(False)
        self.up_19.setCheckable(True)
        self.up_19.setObjectName("up_19")
        self.gridLayout.addWidget(self.up_19, 1, 6, 1, 1)
        self.slider_3 = QtWidgets.QSlider(self.outView)
        self.slider_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_3.sizePolicy().hasHeightForWidth())
        self.slider_3.setSizePolicy(sizePolicy)
        self.slider_3.setMaximum(19)
        self.slider_3.setObjectName("slider_3")
        self.gridLayout.addWidget(self.slider_3, 1, 4, 20, 1)
        self.label_2 = QtWidgets.QLabel(self.outView)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 19, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.outView)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 15, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.outView)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.outView)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.up_1 = QtWidgets.QPushButton(self.outView)
        self.up_1.setCheckable(True)
        self.up_1.setObjectName("up_1")
        self.gridLayout.addWidget(self.up_1, 19, 6, 1, 1)
        self.down_4 = QtWidgets.QPushButton(self.outView)
        self.down_4.setCheckable(True)
        self.down_4.setObjectName("down_4")
        self.gridLayout.addWidget(self.down_4, 16, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.outView)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.down_1 = QtWidgets.QPushButton(self.outView)
        self.down_1.setCheckable(True)
        self.down_1.setObjectName("down_1")
        self.gridLayout.addWidget(self.down_1, 19, 7, 1, 1)
        self.down_5 = QtWidgets.QPushButton(self.outView)
        self.down_5.setCheckable(True)
        self.down_5.setObjectName("down_5")
        self.gridLayout.addWidget(self.down_5, 15, 7, 1, 1)
        self.up_10 = QtWidgets.QPushButton(self.outView)
        self.up_10.setEnabled(True)
        self.up_10.setCheckable(True)
        self.up_10.setObjectName("up_10")
        self.gridLayout.addWidget(self.up_10, 10, 6, 1, 1)
        self.up_0 = QtWidgets.QPushButton(self.outView)
        self.up_0.setCheckable(True)
        self.up_0.setObjectName("up_0")
        self.gridLayout.addWidget(self.up_0, 20, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.outView)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 13, 0, 1, 1)
        self.down_18 = QtWidgets.QPushButton(self.outView)
        self.down_18.setCheckable(True)
        self.down_18.setObjectName("down_18")
        self.gridLayout.addWidget(self.down_18, 2, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.outView)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 16, 0, 1, 1)
        self.down_2 = QtWidgets.QPushButton(self.outView)
        self.down_2.setCheckable(True)
        self.down_2.setObjectName("down_2")
        self.gridLayout.addWidget(self.down_2, 18, 7, 1, 1)
        self.down_10 = QtWidgets.QPushButton(self.outView)
        self.down_10.setCheckable(True)
        self.down_10.setObjectName("down_10")
        self.gridLayout.addWidget(self.down_10, 10, 7, 1, 1)
        self.down_17 = QtWidgets.QPushButton(self.outView)
        self.down_17.setCheckable(True)
        self.down_17.setObjectName("down_17")
        self.gridLayout.addWidget(self.down_17, 3, 7, 1, 1)
        self.up_12 = QtWidgets.QPushButton(self.outView)
        self.up_12.setCheckable(True)
        self.up_12.setObjectName("up_12")
        self.gridLayout.addWidget(self.up_12, 8, 6, 1, 1)
        self.down_15 = QtWidgets.QPushButton(self.outView)
        self.down_15.setCheckable(True)
        self.down_15.setObjectName("down_15")
        self.gridLayout.addWidget(self.down_15, 5, 7, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.outView)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.outView)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.outView)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.down_13 = QtWidgets.QPushButton(self.outView)
        self.down_13.setCheckable(True)
        self.down_13.setObjectName("down_13")
        self.gridLayout.addWidget(self.down_13, 7, 7, 1, 1)
        self.lcd_2 = QtWidgets.QLCDNumber(self.outView)
        self.lcd_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.lcd_2.setDigitCount(2)
        self.lcd_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_2.setProperty("intValue", 1)
        self.lcd_2.setObjectName("lcd_2")
        self.gridLayout.addWidget(self.lcd_2, 0, 3, 1, 1)
        self.up_3 = QtWidgets.QPushButton(self.outView)
        self.up_3.setCheckable(True)
        self.up_3.setObjectName("up_3")
        self.gridLayout.addWidget(self.up_3, 17, 6, 1, 1)
        self.lcd_1 = QtWidgets.QLCDNumber(self.outView)
        self.lcd_1.setStyleSheet("color: rgb(255, 0, 0);")
        self.lcd_1.setDigitCount(2)
        self.lcd_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_1.setProperty("intValue", 1)
        self.lcd_1.setObjectName("lcd_1")
        self.gridLayout.addWidget(self.lcd_1, 0, 2, 1, 1)
        self.lcd_3 = QtWidgets.QLCDNumber(self.outView)
        self.lcd_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.lcd_3.setDigitCount(2)
        self.lcd_3.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_3.setProperty("intValue", 1)
        self.lcd_3.setObjectName("lcd_3")
        self.gridLayout.addWidget(self.lcd_3, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.outView)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 0, 1, 1)
        self.slider_2 = QtWidgets.QSlider(self.outView)
        self.slider_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_2.sizePolicy().hasHeightForWidth())
        self.slider_2.setSizePolicy(sizePolicy)
        self.slider_2.setMaximum(19)
        self.slider_2.setObjectName("slider_2")
        self.gridLayout.addWidget(self.slider_2, 1, 3, 20, 1)
        self.label_7 = QtWidgets.QLabel(self.outView)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 14, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.outView)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 12pt \"微软雅黑 Light\";")
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 20, 0, 1, 1)
        self.ElevatorLayout.addWidget(self.outView, 0, 0, 3, 1)

        self.retranslateUi(Elevator)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Elevator)

    def retranslateUi(self, Elevator):
        _translate = QtCore.QCoreApplication.translate
        Elevator.setWindowTitle(_translate("Elevator", "电梯模拟器"))
        self.inView.setTitle(_translate("Elevator", "电梯内控制按钮"))
        self.elev_0_7.setText(_translate("Elevator", "8"))
        self.elev_0_repair.setText(_translate("Elevator", "修"))
        self.elev_0_15.setText(_translate("Elevator", "16"))
        self.elev_0_4.setText(_translate("Elevator", "5"))
        self.elev_0_1.setText(_translate("Elevator", "2"))
        self.elev_0_10.setText(_translate("Elevator", "11"))
        self.elev_0_8.setText(_translate("Elevator", "9"))
        self.elev_0_2.setText(_translate("Elevator", "3"))
        self.elev_0_6.setText(_translate("Elevator", "7"))
        self.elev_0_17.setText(_translate("Elevator", "18"))
        self.elev_0_11.setText(_translate("Elevator", "12"))
        self.elev_0_12.setText(_translate("Elevator", "13"))
        self.elev_0_close.setText(_translate("Elevator", "><"))
        self.elev_0_19.setText(_translate("Elevator", "20"))
        self.elev_0_open.setText(_translate("Elevator", "<>"))
        self.elev_0_5.setText(_translate("Elevator", "6"))
        self.elev_0_0.setText(_translate("Elevator", "1"))
        self.elev_0_3.setText(_translate("Elevator", "4"))
        self.elev_0_9.setText(_translate("Elevator", "10"))
        self.elev_0_13.setText(_translate("Elevator", "14"))
        self.elev_0_14.setText(_translate("Elevator", "15"))
        self.elev_0_18.setText(_translate("Elevator", "19"))
        self.elev_0_16.setText(_translate("Elevator", "17"))
        self.tab.setTabText(self.tab.indexOf(self.elev0), _translate("Elevator", "电梯1"))
        self.elev_1_open.setText(_translate("Elevator", "<>"))
        self.elev_1_close.setText(_translate("Elevator", "><"))
        self.elev_1_repair.setText(_translate("Elevator", "修"))
        self.elev_1_16.setText(_translate("Elevator", "17"))
        self.elev_1_17.setText(_translate("Elevator", "18"))
        self.elev_1_18.setText(_translate("Elevator", "19"))
        self.elev_1_19.setText(_translate("Elevator", "20"))
        self.elev_1_12.setText(_translate("Elevator", "13"))
        self.elev_1_13.setText(_translate("Elevator", "14"))
        self.elev_1_14.setText(_translate("Elevator", "15"))
        self.elev_1_15.setText(_translate("Elevator", "16"))
        self.elev_1_8.setText(_translate("Elevator", "9"))
        self.elev_1_9.setText(_translate("Elevator", "10"))
        self.elev_1_10.setText(_translate("Elevator", "11"))
        self.elev_1_11.setText(_translate("Elevator", "12"))
        self.elev_1_4.setText(_translate("Elevator", "5"))
        self.elev_1_5.setText(_translate("Elevator", "6"))
        self.elev_1_6.setText(_translate("Elevator", "7"))
        self.elev_1_7.setText(_translate("Elevator", "8"))
        self.elev_1_0.setText(_translate("Elevator", "1"))
        self.elev_1_1.setText(_translate("Elevator", "2"))
        self.elev_1_2.setText(_translate("Elevator", "3"))
        self.elev_1_3.setText(_translate("Elevator", "4"))
        self.tab.setTabText(self.tab.indexOf(self.elev1), _translate("Elevator", "电梯2"))
        self.elev_2_open.setText(_translate("Elevator", "<>"))
        self.elev_2_close.setText(_translate("Elevator", "><"))
        self.elev_2_repair.setText(_translate("Elevator", "修"))
        self.elev_2_16.setText(_translate("Elevator", "17"))
        self.elev_2_17.setText(_translate("Elevator", "18"))
        self.elev_2_18.setText(_translate("Elevator", "19"))
        self.elev_2_19.setText(_translate("Elevator", "20"))
        self.elev_2_12.setText(_translate("Elevator", "13"))
        self.elev_2_13.setText(_translate("Elevator", "14"))
        self.elev_2_14.setText(_translate("Elevator", "15"))
        self.elev_2_15.setText(_translate("Elevator", "16"))
        self.elev_2_8.setText(_translate("Elevator", "9"))
        self.elev_2_9.setText(_translate("Elevator", "10"))
        self.elev_2_10.setText(_translate("Elevator", "11"))
        self.elev_2_11.setText(_translate("Elevator", "12"))
        self.elev_2_4.setText(_translate("Elevator", "5"))
        self.elev_2_5.setText(_translate("Elevator", "6"))
        self.elev_2_6.setText(_translate("Elevator", "7"))
        self.elev_2_7.setText(_translate("Elevator", "8"))
        self.elev_2_0.setText(_translate("Elevator", "1"))
        self.elev_2_1.setText(_translate("Elevator", "2"))
        self.elev_2_2.setText(_translate("Elevator", "3"))
        self.elev_2_3.setText(_translate("Elevator", "4"))
        self.tab.setTabText(self.tab.indexOf(self.elev2), _translate("Elevator", "电梯3"))
        self.elev_3_open.setText(_translate("Elevator", "<>"))
        self.elev_3_close.setText(_translate("Elevator", "><"))
        self.elev_3_repair.setText(_translate("Elevator", "修"))
        self.elev_3_16.setText(_translate("Elevator", "17"))
        self.elev_3_17.setText(_translate("Elevator", "18"))
        self.elev_3_18.setText(_translate("Elevator", "19"))
        self.elev_3_19.setText(_translate("Elevator", "20"))
        self.elev_3_12.setText(_translate("Elevator", "13"))
        self.elev_3_13.setText(_translate("Elevator", "14"))
        self.elev_3_14.setText(_translate("Elevator", "15"))
        self.elev_3_15.setText(_translate("Elevator", "16"))
        self.elev_3_8.setText(_translate("Elevator", "9"))
        self.elev_3_9.setText(_translate("Elevator", "10"))
        self.elev_3_10.setText(_translate("Elevator", "11"))
        self.elev_3_11.setText(_translate("Elevator", "12"))
        self.elev_3_4.setText(_translate("Elevator", "5"))
        self.elev_3_5.setText(_translate("Elevator", "6"))
        self.elev_3_6.setText(_translate("Elevator", "7"))
        self.elev_3_7.setText(_translate("Elevator", "8"))
        self.elev_3_0.setText(_translate("Elevator", "1"))
        self.elev_3_1.setText(_translate("Elevator", "2"))
        self.elev_3_2.setText(_translate("Elevator", "3"))
        self.elev_3_3.setText(_translate("Elevator", "4"))
        self.tab.setTabText(self.tab.indexOf(self.elev3), _translate("Elevator", "电梯4"))
        self.elev_4_open.setText(_translate("Elevator", "<>"))
        self.elev_4_close.setText(_translate("Elevator", "><"))
        self.elev_4_repair.setText(_translate("Elevator", "修"))
        self.elev_4_16.setText(_translate("Elevator", "17"))
        self.elev_4_17.setText(_translate("Elevator", "18"))
        self.elev_4_18.setText(_translate("Elevator", "19"))
        self.elev_4_19.setText(_translate("Elevator", "20"))
        self.elev_4_12.setText(_translate("Elevator", "13"))
        self.elev_4_13.setText(_translate("Elevator", "14"))
        self.elev_4_14.setText(_translate("Elevator", "15"))
        self.elev_4_15.setText(_translate("Elevator", "16"))
        self.elev_4_8.setText(_translate("Elevator", "9"))
        self.elev_4_9.setText(_translate("Elevator", "10"))
        self.elev_4_10.setText(_translate("Elevator", "11"))
        self.elev_4_11.setText(_translate("Elevator", "12"))
        self.elev_4_4.setText(_translate("Elevator", "5"))
        self.elev_4_5.setText(_translate("Elevator", "6"))
        self.elev_4_6.setText(_translate("Elevator", "7"))
        self.elev_4_7.setText(_translate("Elevator", "8"))
        self.elev_4_0.setText(_translate("Elevator", "1"))
        self.elev_4_1.setText(_translate("Elevator", "2"))
        self.elev_4_2.setText(_translate("Elevator", "3"))
        self.elev_4_3.setText(_translate("Elevator", "4"))
        self.tab.setTabText(self.tab.indexOf(self.elev4), _translate("Elevator", "电梯5"))
        self.msgBox.setTitle(_translate("Elevator", "消息窗口"))
        self.outView.setTitle(_translate("Elevator", "电梯实时位置"))
        self.down_3.setText(_translate("Elevator", "▽"))
        self.down_6.setText(_translate("Elevator", "▽"))
        self.up_13.setText(_translate("Elevator", "△"))
        self.down_11.setText(_translate("Elevator", "▽"))
        self.down_12.setText(_translate("Elevator", "▽"))
        self.up_2.setText(_translate("Elevator", "△"))
        self.up_17.setText(_translate("Elevator", "△"))
        self.label_11.setText(_translate("Elevator", "11"))
        self.label_16.setText(_translate("Elevator", "16"))
        self.down_14.setText(_translate("Elevator", "▽"))
        self.up_4.setText(_translate("Elevator", "△"))
        self.up_6.setText(_translate("Elevator", "△"))
        self.label_19.setText(_translate("Elevator", "19"))
        self.down_9.setText(_translate("Elevator", "▽"))
        self.up_18.setText(_translate("Elevator", "△"))
        self.down_16.setText(_translate("Elevator", "▽"))
        self.down_7.setText(_translate("Elevator", "▽"))
        self.down_8.setText(_translate("Elevator", "▽"))
        self.up_7.setText(_translate("Elevator", "△"))
        self.down_19.setText(_translate("Elevator", "▽"))
        self.label_9.setText(_translate("Elevator", "9"))
        self.up_5.setText(_translate("Elevator", "△"))
        self.label_14.setText(_translate("Elevator", "14"))
        self.up_16.setText(_translate("Elevator", "△"))
        self.label_3.setText(_translate("Elevator", "3"))
        self.label_4.setText(_translate("Elevator", "4"))
        self.up_15.setText(_translate("Elevator", "△"))
        self.up_11.setText(_translate("Elevator", "△"))
        self.up_9.setText(_translate("Elevator", "△"))
        self.up_14.setText(_translate("Elevator", "△"))
        self.up_8.setText(_translate("Elevator", "△"))
        self.label_2.setText(_translate("Elevator", "2"))
        self.label_6.setText(_translate("Elevator", "6"))
        self.label_20.setText(_translate("Elevator", "20"))
        self.label_10.setText(_translate("Elevator", "10"))
        self.up_1.setText(_translate("Elevator", "△"))
        self.down_4.setText(_translate("Elevator", "▽"))
        self.label_17.setText(_translate("Elevator", "17"))
        self.down_1.setText(_translate("Elevator", "▽"))
        self.down_5.setText(_translate("Elevator", "▽"))
        self.up_10.setText(_translate("Elevator", "△"))
        self.up_0.setText(_translate("Elevator", "△"))
        self.label_8.setText(_translate("Elevator", "8"))
        self.down_18.setText(_translate("Elevator", "▽"))
        self.label_5.setText(_translate("Elevator", "5"))
        self.down_2.setText(_translate("Elevator", "▽"))
        self.down_10.setText(_translate("Elevator", "▽"))
        self.down_17.setText(_translate("Elevator", "▽"))
        self.up_12.setText(_translate("Elevator", "△"))
        self.down_15.setText(_translate("Elevator", "▽"))
        self.label_13.setText(_translate("Elevator", "13"))
        self.label_18.setText(_translate("Elevator", "18"))
        self.label_15.setText(_translate("Elevator", "15"))
        self.down_13.setText(_translate("Elevator", "▽"))
        self.up_3.setText(_translate("Elevator", "△"))
        self.label_12.setText(_translate("Elevator", "12"))
        self.label_7.setText(_translate("Elevator", "7"))
        self.label_1.setText(_translate("Elevator", "1"))

